import { v4 as uuid } from "uuid";

export const videos = [
  {
    _id: uuid(),
    title: "Vegetable Garden Guide 🥕",
    thumbnail: "http://img.youtube.com/vi/1X6KvqPjk6I/0.jpg",
    creator: "Carrie Rad",
    duration: "11:11",
    icon: "https://yt3.ggpht.com/ytc/AKedOLTyHas9vA4ZpRpzneF-apKG-Oy9rNFinrECXz5Exg=s88-c-k-c0x00ffffff-no-rj",
    category: 'Gardening',
    views: "30k",
    likes: "10k",
    src: "1X6KvqPjk6I",
    date: "Apr 3, 2020"
  },
  {
    _id: uuid(),
    title: "A Paradise called Pollachi 🌴",
    thumbnail: "http://img.youtube.com/vi/UCEWM2Arkfg/0.jpg",
    creator: "Studio A",
    duration: "03:15",
    icon: "https://yt3.ggpht.com/ytc/AKedOLSihKdcnbWBRBMnIzK5P-xHu1HdDWEoOtdnH-ovNg=s88-c-k-c0x00ffffff-no-rj",
    category: 'Travel',
    views: "30k",
    likes: "10k",
    src: "UCEWM2Arkfg",
    date: "Sep 28, 2017"
  },
  {
    _id: uuid(),
    title: "Pop Medley 🎶",
    thumbnail:  "http://img.youtube.com/vi/gTziWaeMYgM/0.jpg",
    creator: "Mackenzie J",
    duration: "05:35",
    icon: "https://yt3.ggpht.com/KQXdZDa8t5VNsa9ibTm_qRb1eEgjixv23VxhJMQiFJBd074HXt5iG0dHEOIY19o10drYH6sy-Q=s88-c-k-c0x00ffffff-no-rj",
    category: 'Music',
    views: "30k",
    likes: "10k",
    src: "gTziWaeMYgM",
    date: "Apr 27, 2015"
  },
  {
    _id: uuid(),
    title: "Garden Makeover 🏡",
    thumbnail: "http://img.youtube.com/vi/Mu2C7y5Dv6o/0.jpg",
    creator: "Omer Calderon",
    duration: "14:39",
    icon: "https://yt3.ggpht.com/20sFbq7JG9WTcweZa4H6Tu9DxkOJJrDbSSzQGF1avjwFwVtXwIb6t1WKgGDNaJpLN0c0J2bSTg=s88-c-k-c0x00ffffff-no-rj",
    category: "Gardening",
    views: "50k",
    likes: "15k",
    src: "Mu2C7y5Dv6o",
    date: "Apr 30, 2021"
  },
  {
    _id: uuid(),
    title: "Balcony Garden 👩🏽‍🌾",
    thumbnail: "http://img.youtube.com/vi/7Cseajqyggg/0.jpg",
    creator: "Xiu House",
    duration: "11:50",
    icon: "https://yt3.ggpht.com/ytc/AKedOLTEMcf6wzZ8fKoGaxbSoUNC28PmGSIRwpDmV5pndQ=s88-c-k-c0x00ffffff-no-rj",
    category: "Gardening",
    views: "50k",
    likes: "15k",
    src: "7Cseajqyggg",
    date: "Jun 12, 2021"
  },
  {
    _id: uuid(),
    title: "Indoor Plants Care 🌿",
    thumbnail: "http://img.youtube.com/vi/bZqJNfZoKRA/0.jpg",
    creator: "Carrie Rad",
    duration: "15:17",
    icon: "https://yt3.ggpht.com/ytc/AKedOLTyHas9vA4ZpRpzneF-apKG-Oy9rNFinrECXz5Exg=s88-c-k-c0x00ffffff-no-rj",
    category: "Gardening",
    views: "50k",
    likes: "15k",
    src: "bZqJNfZoKRA",
    date: "Apr 24, 2020"
  },
  {
    _id: uuid(),
    title: "Travel in India 🌄",
    thumbnail: "http://img.youtube.com/vi/35npVaFGHMY/0.jpg",
    creator: "Huggo Moussy",
    duration: "03:16",
    icon: "https://yt3.ggpht.com/ytc/AKedOLSXHdthfc4QQhT0WAILAlrNppd0ULE0ZA2MRjZX=s88-c-k-c0x00ffffff-no-rj",
    category: "Travel",
    views: "50k",
    likes: "15k",
    src: "35npVaFGHMY",
    date: "Apr 28, 2020"
  },
  {
    _id: uuid(),
    title: "Cebu Adventure 🌊",
    thumbnail: "http://img.youtube.com/vi/GBPY1Ffaf3Q/0.jpg",
    creator: "Benn TK",
    duration: "09:59",
    icon: "https://yt3.ggpht.com/ytc/AKedOLSBQTqYhSUVCb5fl92Mdo4a4nMJKvVLjRIQDmLgCA=s88-c-k-c0x00ffffff-no-rj",
    category: "Travel",
    views: "60k",
    likes: "19k",
    src: "GBPY1Ffaf3Q",
    date: "Apr 28, 2020"
  },
  {
    _id: uuid(),
    title: "How to make Ramen 🍜",
    thumbnail: "http://img.youtube.com/vi/_SpkOoN9oiE/0.jpg",
    creator: "Audrie Storme",
    duration: "12:53",
    icon: "https://yt3.ggpht.com/ytc/AKedOLR4VDg48yVK231OCsGkbQQWmoZIvBz58-Af6IGSCqo=s88-c-k-c0x00ffffff-no-rj",
    category: "Food",
    views: "30k",
    likes: "15k",
    src: "_SpkOoN9oiE",
    date: "Mar 3, 2020"
  },
  {
    _id: uuid(),
    title: "Pan recipes for a Day 🍳",
    thumbnail: "http://img.youtube.com/vi/M2aE613yz-0/0.jpg",
    creator: "Tasty",
    duration: "11:38",
    icon: "https://yt3.ggpht.com/ytc/AKedOLQ9-bwO4U1KuFznuJkDieF9KsLEW_BfsfzMCVUGcA=s88-c-k-c0x00ffffff-no-rj",
    category: "Food",
    views: "45k",
    likes: "15k",
    src: "M2aE613yz-0",
    date: "Jun 18, 2020"
  },
  {
    _id: uuid(),
    title: "3 Ingredients recipes 👨🏽‍🍳",
    thumbnail: "http://img.youtube.com/vi/86QgYvlWEU0/0.jpg",
    creator: "Tasty",
    duration: "12:23",
    icon: "https://yt3.ggpht.com/ytc/AKedOLQ9-bwO4U1KuFznuJkDieF9KsLEW_BfsfzMCVUGcA=s88-c-k-c0x00ffffff-no-rj",
    category: "Food",
    views: "45k",
    likes: "15k",
    src: "86QgYvlWEU0",
    date: "Jun 18, 2020"
  },
  {
    _id: uuid(),
    title: "150 hour chocolate cake 🎂",
    thumbnail: "http://img.youtube.com/vi/rzpJWKvOmdg/0.jpg",
    creator: "Azhvin Zohu",
    duration: "20:41",
    icon: "https://yt3.ggpht.com/CndWqQzkAimSLs6sAA8nNsCPdSLUiPgzXsVlR2nCTzNzuXn3Cf2BjFIP8pYSNQdDgQ92azSC=s88-c-k-c0x00ffffff-no-rj",
    category: "Food",
    views: "45k",
    likes: "15k",
    src: "rzpJWKvOmdg",
    date: "Jun 11, 2021"
  },
  {
    _id: uuid(),
    title: "Finance Management 💸",
    thumbnail: "http://img.youtube.com/vi/YyaVya4YSwU/0.jpg",
    creator: "Matt D'Avella",
    duration: "10:37",
    icon: "https://yt3.ggpht.com/ytc/AKedOLRUZ-Y9amavl7kEI0ZBRH86O6SY8CNwMla_2l57fJ0=s88-c-k-c0x00ffffff-no-rj",
    category: "Money",
    views: "45k",
    likes: "15k",
    src: "YyaVya4YSwU",
    date: "May 29, 2020"
  },
  {
    _id: uuid(),
    title: "How to invest in your 20's 👩🏽‍🎓",
    thumbnail: "http://img.youtube.com/vi/tHxwyWnNu0c/0.jpg",
    creator: "CA Rachana",
    duration: "13:08",
    icon: "https://yt3.ggpht.com/ytc/AKedOLSA3Tow9_-RTNU6WslhjukZuknVu3JzcGiCMumw5g=s88-c-k-c0x00ffffff-no-rj",
    category: "Money",
    views: "45k",
    likes: "15k",
    src: "tHxwyWnNu0c",
    date: "Jun 5, 2021"
  },
  {
    _id: uuid(),
    title: "EPF and PPF - Explained 💱",
    thumbnail: "http://img.youtube.com/vi/RuZU5RNpxTY/0.jpg",
    creator: "warikoo",
    duration: "17:57",
    icon: "https://yt3.ggpht.com/X9eoDIB9cgb1s-kvATRs1lQDcU4Fjc15NDV9s9FF8ck7IsA8u7OdijaernoDV9LLdePgjlt_=s88-c-k-c0x00ffffff-no-rj",
    category: "Money",
    views: "45k",
    likes: "15k",
    src: "RuZU5RNpxTY",
    date: "Oct 7, 2021"
  }
];
